version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - project-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # web UI
    networks:
      - project-network

  # Auth Service
  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - project-network
    command: ["node", "index.js"]

  # Product Service
  product:
    build: ./product
    container_name: product_service
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - project-network
    command: ["node", "index.js"]

  # Order Service
  order:
    build: ./order
    container_name: order_service
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
      product:
        condition: service_started
    networks:
      - project-network
    command: ["node", "index.js"]

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "3003:3003"
    env_file:
      - ./api-gateway/.env
    depends_on:
      auth:
        condition: service_started
      product:
        condition: service_started
      order:
        condition: service_started
    networks:
      - project-network
    command: ["node", "index.js"]

# Volume lưu dữ liệu MongoDB
volumes:
  mongo-data:

# Mạng riêng cho toàn hệ thống
networks:
  project-network:
    driver: bridge
