name: CI/CD Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push Auth Service
      - name: Build & Push Auth Service
        uses: docker/build-push-action@v6
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth_service:latest
          platforms: linux/amd64,linux/arm64

      # Build & push Product Service
      - name: Build & Push Product Service
        uses: docker/build-push-action@v6
        with:
          context: ./product
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product_service:latest
          platforms: linux/amd64,linux/arm64

      # Build & push Order Service
      - name: Build & Push Order Service
        uses: docker/build-push-action@v6
        with:
          context: ./order
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order_service:latest
          platforms: linux/amd64,linux/arm64

      # Build & push API Gateway
      - name: Build & Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api_gateway:latest
          platforms: linux/amd64,linux/arm64